# Generated by Django 3.0.4 on 2020-03-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clintwinsponsor', '0006_auto_20200323_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='sponsorId',
        ),
        migrations.RemoveField(
            model_name='clinicaltrialcriteriaresponse',
            name='trialId',
        ),
        migrations.RemoveField(
            model_name='clinicaltrialcriteriaresponse',
            name='value',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.RemoveField(
            model_name='questionschema',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='questionschema',
            name='responseId',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='ClinicalTrial',
        ),
        migrations.DeleteModel(
            name='ClinicalTrialCriteriaResponse',
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.DeleteModel(
            name='QuestionSchema',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
