# Generated by Django 3.0.4 on 2020-03-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clintwinsponsor', '0009_auto_20200325_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='lastLogin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionschema',
            name='nextQuestion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Next Question'),
        ),
        migrations.AddField(
            model_name='questionschema',
            name='questionText',
            field=models.TextField(blank=True, null=True, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Category ID'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Category Value'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='valueType',
            field=models.CharField(max_length=50, verbose_name='Value Type'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='enrollmentTarget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Enrollment Target'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='exclusionCriteria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exclusion Criteria'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='followUp',
            field=models.TextField(blank=True, null=True, verbose_name='Followup Notes'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='inclusionCriteria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inclusion Criteria'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='objective',
            field=models.CharField(max_length=100, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='recruitmentEndDate',
            field=models.DateField(help_text='MM/DD/YY', verbose_name='Recruitment End Date'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='recruitmentStartDate',
            field=models.DateField(help_text='MM/DD/YY', verbose_name='Recruitment Start Date'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='sponsorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clintwinsponsor.Sponsor'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Trial Title'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='trialId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Trial ID'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='clinicaltrialcriteriaresponse',
            name='responseId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Response ID'),
        ),
        migrations.AlterField(
            model_name='clinicaltrialcriteriaresponse',
            name='trialId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clintwinsponsor.ClinicalTrial'),
        ),
        migrations.AlterField(
            model_name='clinicaltrialcriteriaresponse',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='criteriaId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Criteria ID'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Criteria Name'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Criteria Value'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='valueType',
            field=models.CharField(max_length=50, verbose_name='Criteria Type'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dateBirth',
            field=models.DateField(help_text='MM/DD/YY', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dateDeregistered',
            field=models.DateField(blank=True, help_text='MM/DD/YY', null=True, verbose_name='Date of De-Registration'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dateRegistered',
            field=models.DateField(help_text='MM/DD/YY', verbose_name='Date of Registration'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='height',
            field=models.FloatField(verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Lasst Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participantId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Participant ID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.IntegerField(verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='weight',
            field=models.FloatField(verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='questionschema',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clintwinsponsor.Categories'),
        ),
        migrations.AlterField(
            model_name='questionschema',
            name='questionId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='questionschema',
            name='responseId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clintwinsponsor.ClinicalTrialCriteriaResponse'),
        ),
        migrations.AlterField(
            model_name='questionschema',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='OrganizationName',
            field=models.CharField(help_text='Name of Sponsor', max_length=50, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='contactPerson',
            field=models.CharField(max_length=50, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='dateDeregistered',
            field=models.DateField(blank=True, null=True, verbose_name='Date of De-Regstration'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='dateRegistered',
            field=models.DateField(verbose_name='Date of Registration'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.IntegerField(verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsorId',
            field=models.CharField(help_text='Unique Sponsor ID', max_length=30, primary_key=True, serialize=False, verbose_name='Sponsor ID'),
        ),
    ]
